export type Course = {
  id: string;
  level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
  accent: "violet" | "teal" | "rose" | "green" | "gold";
  icon: string;
  tag: string;
  rating: string;
  reviews: string;
  title: string;
  byline: string;
  duration: string;
  price: string;
  oldPrice: string;
  lessons?: string;
  instructor?: string;
  certificate?: string;
  language?: string;
  access?: string;
  videoUrl: string;
  previewSeconds?: number;
  description?: string;
  learnings?: string[];
  relatedCourses?: string[];
};

export const COURSES: Course[] = [
  {
    id: "ml-bootcamp-2025",
    level: "BEGINNER",
    accent: "violet",
    icon: "🤖",
    tag: "AI & ML",
    rating: "4.9",
    reviews: "12.4k",
    title: "Complete Machine Learning Bootcamp 2025",
    byline: "by Dr. Sarah Chen · 48.2k students",
    duration: "42h",
    price: "$89",
    oldPrice: "$109",
    lessons: "282 lectures",
    instructor: "Dr. Sarah Chen",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=aircAruvnKk",
    previewSeconds: 300,
    description: "Master machine learning from fundamentals to advanced techniques. This bootcamp covers Python, scikit-learn, TensorFlow, deep learning, natural networks, and ML deployment to production of scale.",
    learnings: [
      "Build ML models from fundamentals",
      "Deep learning with TensorFlow",
      "Natural Language Processing",
      "Computer Vision & CNNs",
      "Deploy ML models to production",
      "Master Python for data science",
    ],
  },
  {
    id: "react-nextjs-2025",
    level: "INTERMEDIATE",
    accent: "teal",
    icon: "⚛️",
    tag: "Development",
    rating: "4.8",
    reviews: "9.8k",
    title: "React & Next.js Masterclass 2025",
    byline: "by Marcus Reid · 62.1k students",
    duration: "38h",
    price: "$79",
    oldPrice: "$159",
    lessons: "256 lectures",
    instructor: "Marcus Reid",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=w7ejDZ8SWv8",
    previewSeconds: 300,
    description: "Learn React and Next.js from scratch. Build full-stack applications with React hooks, state management, server-side rendering, and API routes.",
    learnings: [
      "React fundamentals and hooks",
      "Next.js framework mastery",
      "Server-side rendering",
      "API routes & backend integration",
      "Database integration",
      "Deploy to production",
    ],
  },
  {
    id: "uiux-design-bootcamp",
    level: "BEGINNER",
    accent: "rose",
    icon: "🎨",
    tag: "Design",
    rating: "4.9",
    reviews: "8.2k",
    title: "Complete UI/UX Design Bootcamp",
    byline: "by Aisha Nwosu · 31.4k students",
    duration: "28h",
    price: "$99",
    oldPrice: "$189",
    lessons: "198 lectures",
    instructor: "Aisha Nwosu",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=c9Wg6Cb_YlU",
    previewSeconds: 300,
    description: "Learn UI/UX design principles and tools. Master Figma, design systems, prototyping, and user research.",
    learnings: [
      "UI/UX design principles",
      "Figma mastery",
      "Design systems",
      "User research methods",
      "Prototyping & testing",
      "Build design portfolio",
    ],
  },
  {
    id: "python-data-science",
    level: "BEGINNER",
    accent: "green",
    icon: "📊",
    tag: "Data Science",
    rating: "4.7",
    reviews: "15.1k",
    title: "Python for Data Science & ML",
    byline: "by Tom Katsuiki · 55.3k students",
    duration: "35h",
    price: "$69",
    oldPrice: "$149",
    lessons: "234 lectures",
    instructor: "Tom Katsuiki",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=LHBE6Q9XlzI",
    previewSeconds: 300,
    description: "Learn Python, NumPy, Pandas, and Matplotlib for data science and analysis.",
    learnings: [
      "Python programming basics",
      "NumPy and Pandas",
      "Data visualization",
      "Statistical analysis",
      "Data cleaning",
      "Real-world projects",
    ],
  },
  {
    id: "aws-cloud-architect",
    level: "EXPERT",
    accent: "gold",
    icon: "☁️",
    tag: "Cloud & DevOps",
    rating: "4.8",
    reviews: "6.4k",
    title: "AWS Cloud Architect Certification",
    byline: "by Priya Sharma · 24.1k students",
    duration: "30h",
    price: "$119",
    oldPrice: "$189",
    lessons: "215 lectures",
    instructor: "Priya Sharma",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=Ia-UEYYR44s",
    previewSeconds: 300,
    description: "Prepare for AWS Solutions Architect exam. Learn AWS architecture, security, and best practices.",
    learnings: [
      "AWS core services",
      "Architecture patterns",
      "Security & compliance",
      "Scalability & performance",
      "Cost optimization",
      "Exam preparation",
    ],
  },
  {
    id: "ethical-hacking",
    level: "ADVANCED",
    accent: "teal",
    icon: "🔒",
    tag: "Cybersecurity",
    rating: "4.8",
    reviews: "5.2k",
    title: "Ethical Hacking & Cybersecurity",
    byline: "by Daniel Cross · 22.8k students",
    duration: "32h",
    price: "$89",
    oldPrice: "$169",
    lessons: "224 lectures",
    instructor: "Daniel Cross",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=3Kq1MIfTWCE",
    previewSeconds: 300,
    description: "Learn ethical hacking, penetration testing, and network security.",
    learnings: [
      "Network fundamentals",
      "Penetration testing",
      "Web application security",
      "Cryptography",
      "Incident response",
      "Security tools & techniques",
    ],
  },
  {
    id: "ios-android-dev",
    level: "INTERMEDIATE",
    accent: "violet",
    icon: "📱",
    tag: "Mobile Dev",
    rating: "4.7",
    reviews: "4.8k",
    title: "iOS & Android App Development",
    byline: "by Yuki Tanaka · 18.3k students",
    duration: "26h",
    price: "$99",
    oldPrice: "$179",
    lessons: "187 lectures",
    instructor: "Yuki Tanaka",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=VPvVD8t02U8",
    previewSeconds: 300,
    description: "Build native iOS and Android apps. Learn Swift and Kotlin.",
    learnings: [
      "Swift for iOS development",
      "Kotlin for Android",
      "Mobile UI design",
      "APIs & backend",
      "App store deployment",
      "Mobile performance",
    ],
  },
  {
    id: "deep-learning-pytorch",
    level: "ADVANCED",
    accent: "rose",
    icon: "🧠",
    tag: "AI & ML",
    rating: "4.8",
    reviews: "7.1k",
    title: "Deep Learning with PyTorch",
    byline: "by Dr. Sarah Chen · 29.6k students",
    duration: "29h",
    price: "$109",
    oldPrice: "$199",
    lessons: "206 lectures",
    instructor: "Dr. Sarah Chen",
    certificate: "Yes, Verified",
    language: "English",
    access: "Lifetime",
    videoUrl: "https://www.youtube.com/watch?v=V_xro1bcAuA",
    previewSeconds: 300,
    description: "Master deep learning with PyTorch framework. Build neural networks and advanced models.",
    learnings: [
      "PyTorch fundamentals",
      "Neural network architectures",
      "CNNs & RNNs",
      "Transformers",
      "Model optimization",
      "Production deployment",
    ],
  },
];

export const FILTER_CATEGORIES = [
  { label: "Development", count: 342 },
  { label: "Design", count: 218 },
  { label: "AI & ML", count: 156 },
  { label: "Data Science", count: 205 },
  { label: "Business", count: 112 },
] as const;

export const FILTER_LEVELS = [
  { label: "Beginner", count: 280 },
  { label: "Intermediate", count: 140 },
  { label: "Advanced", count: 60 },
] as const;

export function getCourseById(id: string): Course | undefined {
  return COURSES.find(course => course.id === id);
}
